a.out: main.cpp AnalyzerHTML.cpp fileReader/FileReader.cpp scanner/Scanner.cpp parser/Parser.cpp tokens/Token.cpp errors/Error.cpp
	g++ main.cpp AnalyzerHTML.cpp fileReader/FileReader.cpp scanner/Scanner.cpp parser/Parser.cpp tokens/Token.cpp errors/Error.cpp -o a.out
